name = "Apollo-213"
mc_version = "1.20.1"

[jar]
type = "fabric"
loader = "0.15.11"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
memory = "12G"

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "HaaH232J"
version = "vPTIVHrC"

[[mods]]
type = "modrinth"
id = "nmDcB62a"
version = "fh7tdNlS"

[[clientsidemods]]
type = "modrinth"
id = "ZfQ3kTvR"
version = "wgtrj8HS"
optional = false
desc = "launch quicker tha game"

[[clientsidemods]]
type = "modrinth"
id = "1IjD5062"
version = "84Zs6tNo"
optional = false
desc = "shit tha works with optifine now works without it"

[[mods]]
type = "modrinth"
id = "fALzjamp"
version = "NHWYq9at"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "ZSNsJrPI"

[[mods]]
type = "modrinth"
id = "CVT4pFB2"
version = "2o0oW8Yv"

[[clientsidemods]]
type = "modrinth"
id = "AANobbMI"
version = "mhZtY2lR"
optional = false
desc = "Sodium (performance mod)"

[[clientsidemods]]
type = "modrinth"
id = "3qsfQtE9"
version = "Rduo9X24"
optional = true
desc = "high quality screenshots cause why not"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "J3FLptsi"

[[mods]]
type = "modrinth"
id = "NNAgCjsB"
version = "frGGaFrx"

[[mods]]
type = "modrinth"
id = "1eAoo2KR"
version = "RXrT2ogA"

[[clientsidemods]]
type = "modrinth"
id = "YL57xq9U"
version = "KHQ2Hnpt"
optional = false
desc = "iris, tha core of the shaders"

[[clientsidemods]]
type = "modrinth"
id = "w7ThoJFB"
version = "66iHgfN8"
optional = false
desc = "zoom how xu want"

[[clientsidemods]]
type = "modrinth"
id = "PtjYWJkn"
version = "I7ggF6B5"
optional = false
desc = "sodium extra options nd features"

[[mods]]
type = "modrinth"
id = "Ha28R6CL"
version = "afsFajDC"

# [[clientsidemods]]
# type = "modrinth"
# id = "Q1vvjJYV"
# version = "k7zNmcFF"
# optional = true
# desc = "shaderpack"

[[clientsidemods]]
type = "modrinth"
id = "yBW8D80W"
version = "mYl4RvKg"
optional = false
desc = "dinamic lighting, everybody needs it"

[[mods]]
type = "modrinth"
id = "x1hIzbuY"
version = "tNgyOUMr"
optional = true
desc = "has fast in tha name so here it is"

[[clientsidemods]]
type = "modrinth"
id = "51shyZVL"
version = "3m5znPWm"
optional = false
desc = "culls shit for performace"

[[clientsidemods]]
type = "modrinth"
id = "89Wsn8GD"
version = "z2zOEvPP"
optional = false
desc = "allows use of custom capes"

# [[clientsidemods]]
# type = "modrinth"
# id = "D5k8BTVz"
# version = "qwUpiwSm"
# optional = true
# desc = "shaderpack"

[[mods]]
type = "modrinth"
id = "EsAfCjCV"
version = "xcauwnEB"

[[mods]]
type = "modrinth"
id = "NRjRiSSD"
version = "5xvCCRjJ"

# [[clientsidemods]]
# type = "modrinth"
# id = "sclYVqbt"
# version = "QAc0MeLZ"
# optional = true
# desc = "shaderpack"

[[clientsidemods]]
type = "modrinth"
id = "rrwQMaWQ"
version = "jqQWbvCg"
optional = true
desc = "Camera Utils"

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "ba99D9Qf"

[[mods]]
type = "modrinth"
id = "VSNURh3q"
version = "QZ5cUNXs"

[[clientsidemods]]
type = "modrinth"
id = "Orvt0mRa"
version = "Aouse6P7"
optional = false
desc = "Indium, look it up, imma not write a exaustive desc here"

[[mods]]
type = "modrinth"
id = "LQ3K71Q1"
version = "48hFxWw7"
optional = false
desc = "o shit minecra not running on tha background¿¿¿"

# [[clientsidemods]]
# type = "modrinth"
# id = "BS9T99lD"
# version = "AnhOHG4D"
# optional = true
# desc = "shaderpack"
#
# [[clientsidemods]]
# type = "modrinth"
# id = "lLqFfGNs"
# version = "Dn4cGSpn"
# optional = true
# desc = "shaderpack"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "unerR5MN"

[[mods]]
type = "modrinth"
id = "hvFnDODi"
version = "4SHylIO9"

[[clientsidemods]]
type = "modrinth"
id = "QdG47OkI"
version = "GkLb4bRl"
optional = false
desc = "fixes models"

[[clientsidemods]]
type = "modrinth"
id = "mOgUt4GM"
version = "lEkperf6"
optional = false
desc = "Adds a mod menu to list installed mods"

# [[clientsidemods]]
# type = "modrinth"
# id = "dspVZXKP"
# version = "dsyjkZFg"
# optional = true
# desc = "shaderpack"

[[mods]]
type = "modrinth"
id = "qANg5Jrr"
version = "vVFlVRt7"

[[mods]]
type = "modrinth"
id = "J81TRJWm"
version = "RlBGFlWp"

[[clientsidemods]]
type = "modrinth"
id = "iG6ZHsUV"
version = "TFvkv8XK"
optional = false
desc = "more fps, less leaves, better experience"

[[mods]]
type = "modrinth"
id = "9eGKb6K1"
version = "nBaghNgP"

[[mods]]
type = "modrinth"
id = "lWDHr9jE"
version = "PFg0zBtc"

[[clientsidemods]]
type = "modrinth"
id = "Bh37bMuy"
version = "Rc9pkPug"
optional = false
desc = "better graphics option's menu"

[[mods]]
type = "modrinth"
id = "KuNKN7d2"
version = "uTdy9g9c"

[[mods]]
type = "modrinth"
id = "FimwF33K"
version = "JFNunyDW"
